### ISSUE TITLE
Combine lazyframe or read multiple spreadsheet in one lazyframe for easy query.

### ISSUE THREAD

**Issue by Reece030130** [zazwaz12/CITS3200---National-Housing-Simulation#81] opened 2024-09-26 04:04 UTC
# **Feature Summary**
G13A G13B G13C G13D should conbine to one lazyframe with key G13. Some categories breaked into two or more files which may cause the error when query.

## **Key Requirements**
- [ ] combine exist lazyframe
- [ ] read multiple spreadsheet into one lazyframe. 
![Screenshot 2024-09-26 120246](https://github.com/user-attachments/assets/421985ee-3bc0-46e7-8675-6dde7d703452)

**Comment by SodaVolcano** [comment] 2024-09-29 04:19
this seem to be a duplicate of #76 ?

**Comment by Reece030130** [comment] 2024-09-29 07:15
#76

**Closed** 2024-09-29 07:15 UTC
